### Site metadata ###

site_name: SpeechmetryFlow
site_description: SpeechmetryFlow Documentation
site_url: https://lingualab.github.io/speechmetryflow/
repo_url: https://github.com/lingualab/speechmetryflow
edit_uri: edit/master/docs/docs

### Build settings ###

plugins:
  - table-reader

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

nav:
  - Documentation:
    - index.md
    - installation.md
    - getting-started.md
  - Text Features:
    - text/speech-production.md
    - text/lexical.md
    - text/semantic.md
    - text/syntaxic.md
    - text/pragmatic.md
  - Audio Features:
    - audio/parselmouth.md
    - audio/opensmile.md
    - audio/uhmometer.md
  - Changelog: changelog.md
