### Site metadata ###

site_name: SpeechmetryFlow
site_description: SpeechmetryFlow Documentation
site_url: https://lingualab.github.io/speechmetryflow/
repo_url: https://github.com/lingualab/speechmetryflow
edit_uri: edit/master/docs/docs

### Build settings ###

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

nav:
  - Home: index.md
  - Text Features:
    - en/lingualab-text-production.md
    - en/lingualab-text-lexical.md
    - en/lingualab-text-semantic.md
    - en/lingualab-text-syntaxic.md
    - en/lingualab-text-pragmatic.md
  - Audio Features:
    - en/parselmouth-audio.md
    - en/opensmile-audio.md
    - en/uhmometer-audio.md
